from typing import List, Optional, Tuple, Union, Iterable

__version__: str

class Side:
    Buy: Side
    Sell: Side

class OrderStatus:
    New: OrderStatus
    PartiallyFilled: OrderStatus
    Filled: OrderStatus
    Cancelled: OrderStatus
    Rejected: OrderStatus
    Resting: OrderStatus

class OrderType:
    Limit: OrderType

class RejectReason:
    NoReject: RejectReason
    None_: RejectReason
    DuplicateOrderId: RejectReason
    UnknownOrder: RejectReason
    InvalidPrice: RejectReason
    InvalidQuantity: RejectReason
    OrderAlreadyFilled: RejectReason
    OrderAlreadyCancelled: RejectReason
    InvalidStateTransition: RejectReason

Buy: Side
Sell: Side
New: OrderStatus
PartiallyFilled: OrderStatus
Filled: OrderStatus
Cancelled: OrderStatus
Rejected: OrderStatus
Resting: OrderStatus
Limit: OrderType

class Order:
    def __init__(self, order_id: int, side: Side, price: int, quantity: int, sequence_number: int = 0) -> None: ...
    @property
    def order_id(self) -> int: ...
    @property
    def side(self) -> Side: ...
    @property
    def price(self) -> int: ...
    @property
    def initial_quantity(self) -> int: ...
    @property
    def remaining_quantity(self) -> int: ...
    @property
    def filled_quantity(self) -> int: ...
    @property
    def status(self) -> OrderStatus: ...
    @property
    def sequence_number(self) -> int: ...
    def is_active(self) -> bool: ...
    def is_terminal(self) -> bool: ...
    def is_filled(self) -> bool: ...

class Trade:
    def __init__(
        self,
        trade_id: int = 0,
        maker_order_id: int = 0,
        taker_order_id: int = 0,
        maker_side: Side = Side.Buy,
        price: int = 0,
        quantity: int = 0,
        sequence_number: int = 0,
    ) -> None: ...
    trade_id: int
    maker_order_id: int
    taker_order_id: int
    maker_side: Side
    price: int
    quantity: int
    sequence_number: int

class ExecutionReport:
    order_id: int
    status: OrderStatus
    reject_reason: RejectReason
    remaining_quantity: int
    filled_quantity: int
    price: int
    side: Side
    sequence_number: int
    trades: List[Trade]

class LevelInfo:
    def __init__(self, price: int = 0, total_quantity: int = 0, order_count: int = 0) -> None: ...
    price: int
    total_quantity: int
    order_count: int

class BatchOrder:
    def __init__(self, order_id: int, side: Side, price: int, quantity: int) -> None: ...
    order_id: int
    side: Side
    price: int
    quantity: int

class CreateOrderCommand:
    def __init__(self, order_id: int, side: Side, price: int, quantity: int) -> None: ...
    order_id: int
    side: Side
    price: int
    quantity: int

class CancelOrderCommand:
    def __init__(self, order_id: int) -> None: ...
    order_id: int

class ModifyOrderCommand:
    def __init__(self, order_id: int, new_price: int, new_quantity: int) -> None: ...
    order_id: int
    new_price: int
    new_quantity: int

class OrderCommand:
    def __init__(
        self,
        sequence_number: int = 0,
        payload: Union[CreateOrderCommand, CancelOrderCommand, ModifyOrderCommand] = ...,
    ) -> None: ...
    sequence_number: int
    payload: Union[CreateOrderCommand, CancelOrderCommand, ModifyOrderCommand]

class ReferenceMatchingEngine:
    def __init__(self) -> None: ...
    def submit_order(self, order_id: int, side: Side, price: int, quantity: int) -> ExecutionReport: ...
    def cancel_order(self, order_id: int) -> ExecutionReport: ...
    def modify_order(self, order_id: int, new_price: int, new_quantity: int) -> ExecutionReport: ...
    def process_command(self, command: OrderCommand) -> ExecutionReport: ...
    def reset(self) -> None: ...
    def current_sequence(self) -> int: ...
    def current_trade_id(self) -> int: ...
    def best_bid_price(self) -> Optional[int]: ...
    def best_ask_price(self) -> Optional[int]: ...
    def best_bid_quantity(self) -> Optional[int]: ...
    def best_ask_quantity(self) -> Optional[int]: ...
    def total_bid_volume(self) -> int: ...
    def total_ask_volume(self) -> int: ...
    def total_orders(self) -> int: ...
    def is_empty(self) -> bool: ...
    def get_bids(self, max_levels: int = 0) -> List[LevelInfo]: ...
    def get_asks(self, max_levels: int = 0) -> List[LevelInfo]: ...
    def canonical_hash(self) -> int: ...
    def serialize_state(self) -> bytes: ...
    def audit(self) -> Tuple[bool, str]: ...
    def submit_batch(self, orders: Iterable[Union[BatchOrder, Tuple[int, Side, int, int]]]) -> List[ExecutionReport]: ...
    def process_commands_batch(self, commands: List[OrderCommand]) -> List[ExecutionReport]: ...

class OptimizedMatchingEngine:
    def __init__(self, initial_capacity: int = 65536) -> None: ...
    def submit_order(self, order_id: int, side: Side, price: int, quantity: int) -> ExecutionReport: ...
    def cancel_order(self, order_id: int) -> ExecutionReport: ...
    def modify_order(self, order_id: int, new_price: int, new_quantity: int) -> ExecutionReport: ...
    def process_command(self, command: OrderCommand) -> ExecutionReport: ...
    def reset(self) -> None: ...
    def current_sequence(self) -> int: ...
    def current_trade_id(self) -> int: ...
    def best_bid_price(self) -> Optional[int]: ...
    def best_ask_price(self) -> Optional[int]: ...
    def best_bid_quantity(self) -> Optional[int]: ...
    def best_ask_quantity(self) -> Optional[int]: ...
    def total_bid_volume(self) -> int: ...
    def total_ask_volume(self) -> int: ...
    def total_orders(self) -> int: ...
    def is_empty(self) -> bool: ...
    def get_bids(self, max_levels: int = 0) -> List[LevelInfo]: ...
    def get_asks(self, max_levels: int = 0) -> List[LevelInfo]: ...
    def canonical_hash(self) -> int: ...
    def serialize_state(self) -> bytes: ...
    def audit(self) -> Tuple[bool, str]: ...
    def submit_batch(self, orders: Iterable[Union[BatchOrder, Tuple[int, Side, int, int]]]) -> List[ExecutionReport]: ...
    def process_commands_batch(self, commands: List[OrderCommand]) -> List[ExecutionReport]: ...

MatchingEngine = OptimizedMatchingEngine

class CanonicalState:
    @staticmethod
    def hash_reference(engine: ReferenceMatchingEngine) -> int: ...
    @staticmethod
    def hash_optimized(engine: OptimizedMatchingEngine) -> int: ...
    @staticmethod
    def to_hex(hash: int) -> str: ...

class ReplayResult:
    final_hash: int
    execution_reports: List[ExecutionReport]
    all_trades: List[Trade]
    invariants_satisfied: bool
    failure_reason: str

class ReplayEngine:
    @staticmethod
    def replay_reference(commands: List[OrderCommand]) -> ReplayResult: ...
    @staticmethod
    def replay_optimized(commands: List[OrderCommand]) -> ReplayResult: ...
    @staticmethod
    def verify_determinism(commands: List[OrderCommand]) -> bool: ...
